CREATE OR ALTER PROCEDURE UP_INSERTEMPLOYEES
AS
	DECLARE @EMPLOYEES_QTY AS INT 
	DECLARE @COUNTER AS INT
	DECLARE @ID_EMPLOYEE AS INT
	DECLARE @NAME AS VARCHAR(25)
	DECLARE @LAST AS VARCHAR(25)
	DECLARE @SSN AS VARCHAR(9)
	DECLARE @DATE AS SMALLDATETIME
	DECLARE @ID_DEPARTMENT AS TINYINT
	DECLARE @ID_SUPERVISOR AS INT
	DECLARE @ISACTIVE AS BIT

	SET @EMPLOYEES_QTY = 1000
	SET @COUNTER = 0

	TRUNCATE TABLE EMPLOYEE

	WHILE ( @COUNTER < @EMPLOYEES_QTY)
	BEGIN
		SELECT @ID_EMPLOYEE= @COUNTER+1 
		SELECT @NAME = [Name] FROM SampleData.dbo.[Name] WHERE ID = ROUND(RAND()*100,0)
		SELECT @LAST = [LastName] FROM SampleData.dbo.[LastName] WHERE ID = ROUND(RAND()*100,0)
		SELECT @SSN = SUBSTRING(@name,0,3) + SUBSTRING(@Last,0,3) + SUBSTRING(@name,1,2)+ SUBSTRING(@LAST,3,1)
		SELECT @DATE = DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 3650), '2000-01-01')
		SELECT @ID_DEPARTMENT = ROUND(RAND()*10,0)
		SELECT @ID_SUPERVISOR = ROUND(RAND()*100,0)
		SELECT @ISACTIVE = CRYPT_GEN_RANDOM(1)%2
			INSERT INTO Employee VALUES (@ID_EMPLOYEE,@Name, @LAST, @SSN,@ID_DEPARTMENT, @ID_SUPERVISOR,@DATE,@ISACTIVE )
		SET @COUNTER = @COUNTER + 1 
	END


