CREATE OR ALTER PROCEDURE UP_INSERTSALARIES
AS
	DECLARE @ID_EMPLOYEE AS INT
	DECLARE @SALARY AS INT
	DECLARE @COUNTER AS INT
	DECLARE @ROWS AS INT
	DECLARE @STARTDATE AS SMALLDATETIME

	SET @COUNTER = 0
	SET @ROWS = 5000

	TRUNCATE TABLE EMPLOYEE_SALARIES

		WHILE ( @COUNTER < @ROWS)
		BEGIN
			SELECT @ID_EMPLOYEE= ROUND(RAND()*1000,0)
			SELECT @SALARY = ROUND(RAND()*10000,0)
			SELECT @STARTDATE = DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 3650), '2000-01-01')
			INSERT INTO EMPLOYEE_SALARIES VALUES (@ID_EMPLOYEE, @SALARY, @STARTDATE)
			SET @COUNTER = @COUNTER + 1 
		END



