USE SampleData;
GO
IF OBJECT_ID(N'dbo.LastName', N'U') IS NOT NULL  
   DROP TABLE [dbo].[LastName];  
GO



CREATE TABLE LastName(
	ID  INT,
	LastName  VARCHAR(25)
);

INSERT INTO LastName VALUES (1,'GARCIA');
INSERT INTO LastName VALUES (2,'RODRIGUEZ');
INSERT INTO LastName VALUES (3,'GONZALEZ');
INSERT INTO LastName VALUES (4,'FERNANDEZ');
INSERT INTO LastName VALUES (5,'LOPEZ');
INSERT INTO LastName VALUES (6,'MARTINEZ');
INSERT INTO LastName VALUES (7,'SANCHEZ');
INSERT INTO LastName VALUES (8,'PEREZ');
INSERT INTO LastName VALUES (9,'GOMEZ');
INSERT INTO LastName VALUES (10,'MARTIN');
INSERT INTO LastName VALUES (11,'JIMENEZ');
INSERT INTO LastName VALUES (12,'HERNANDEZ');
INSERT INTO LastName VALUES (13,'RUIZ');
INSERT INTO LastName VALUES (14,'DIAZ');
INSERT INTO LastName VALUES (15,'MORENO');
INSERT INTO LastName VALUES (16,'MU�OZ');
INSERT INTO LastName VALUES (17,'ALVAREZ');
INSERT INTO LastName VALUES (18,'ROMERO');
INSERT INTO LastName VALUES (19,'GUTIERREZ');
INSERT INTO LastName VALUES (20,'ALONSO');
INSERT INTO LastName VALUES (21,'NAVARRO');
INSERT INTO LastName VALUES (22,'TORRES');
INSERT INTO LastName VALUES (23,'DOMINGUEZ');
INSERT INTO LastName VALUES (24,'RAMOS');
INSERT INTO LastName VALUES (25,'VAZQUEZ');
INSERT INTO LastName VALUES (26,'RAMIREZ');
INSERT INTO LastName VALUES (27,'GIL');
INSERT INTO LastName VALUES (28,'SERRANO');
INSERT INTO LastName VALUES (29,'MORALES');
INSERT INTO LastName VALUES (30,'MOLINA');
INSERT INTO LastName VALUES (31,'BLANCO');
INSERT INTO LastName VALUES (32,'SUAREZ');
INSERT INTO LastName VALUES (33,'CASTRO');
INSERT INTO LastName VALUES (34,'ORTEGA');
INSERT INTO LastName VALUES (35,'DELGADO');
INSERT INTO LastName VALUES (36,'ORTIZ');
INSERT INTO LastName VALUES (37,'MARIN');
INSERT INTO LastName VALUES (38,'RUBIO');
INSERT INTO LastName VALUES (39,'NU�EZ');
INSERT INTO LastName VALUES (40,'SANZ');
INSERT INTO LastName VALUES (41,'MEDINA');
INSERT INTO LastName VALUES (42,'IGLESIAS');
INSERT INTO LastName VALUES (43,'CASTILLO');
INSERT INTO LastName VALUES (44,'CORTES');
INSERT INTO LastName VALUES (45,'GARRIDO');
INSERT INTO LastName VALUES (46,'SANTOS');
INSERT INTO LastName VALUES (47,'GUERRERO');
INSERT INTO LastName VALUES (48,'LOZANO');
INSERT INTO LastName VALUES (49,'CANO');
INSERT INTO LastName VALUES (50,'MENDEZ');
INSERT INTO LastName VALUES (51,'CRUZ');
INSERT INTO LastName VALUES (52,'PRIETO');
INSERT INTO LastName VALUES (53,'FLORES');
INSERT INTO LastName VALUES (54,'HERRERA');
INSERT INTO LastName VALUES (55,'PE�A');
INSERT INTO LastName VALUES (56,'LEON');
INSERT INTO LastName VALUES (57,'MARQUEZ');
INSERT INTO LastName VALUES (58,'CABRERA');
INSERT INTO LastName VALUES (59,'GALLEGO');
INSERT INTO LastName VALUES (60,'CALVO');
INSERT INTO LastName VALUES (61,'VIDAL');
INSERT INTO LastName VALUES (62,'CAMPOS');
INSERT INTO LastName VALUES (63,'REYES');
INSERT INTO LastName VALUES (64,'VEGA');
INSERT INTO LastName VALUES (65,'FUENTES');
INSERT INTO LastName VALUES (66,'CARRASCO');
INSERT INTO LastName VALUES (67,'DIEZ');
INSERT INTO LastName VALUES (68,'AGUILAR');
INSERT INTO LastName VALUES (69,'CABALLERO');
INSERT INTO LastName VALUES (70,'NIETO');
INSERT INTO LastName VALUES (71,'SANTANA');
INSERT INTO LastName VALUES (72,'PASCUAL');
INSERT INTO LastName VALUES (73,'HERRERO');
INSERT INTO LastName VALUES (74,'VARGAS');
INSERT INTO LastName VALUES (75,'GIMENEZ');
INSERT INTO LastName VALUES (76,'MONTERO');
INSERT INTO LastName VALUES (77,'HIDALGO');
INSERT INTO LastName VALUES (78,'LORENZO');
INSERT INTO LastName VALUES (79,'SANTIAGO');
INSERT INTO LastName VALUES (80,'IBA�EZ');
INSERT INTO LastName VALUES (81,'DURAN');
INSERT INTO LastName VALUES (82,'BENITEZ');
INSERT INTO LastName VALUES (83,'FERRER');
INSERT INTO LastName VALUES (84,'ARIAS');
INSERT INTO LastName VALUES (85,'MORA');
INSERT INTO LastName VALUES (86,'CARMONA');
INSERT INTO LastName VALUES (87,'VICENTE');
INSERT INTO LastName VALUES (88,'ROJAS');
INSERT INTO LastName VALUES (89,'SOTO');
INSERT INTO LastName VALUES (90,'CRESPO');
INSERT INTO LastName VALUES (91,'ROMAN');
INSERT INTO LastName VALUES (92,'PASTOR');
INSERT INTO LastName VALUES (93,'VELASCO');
INSERT INTO LastName VALUES (94,'PARRA');
INSERT INTO LastName VALUES (95,'SAEZ');
INSERT INTO LastName VALUES (96,'MOYA');
INSERT INTO LastName VALUES (97,'BRAVO');
INSERT INTO LastName VALUES (98,'SOLER');
INSERT INTO LastName VALUES (99,'GALLARDO');
INSERT INTO LastName VALUES (100,'RIVERA');

