USE [Interview]
GO
/****** Object:  StoredProcedure [dbo].[UP_INSERTDUPLICATES]    Script Date: 1/14/2023 8:17:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER   PROCEDURE [dbo].[UP_INSERTDUPLICATES]
AS

	DECLARE @NAME AS VARCHAR (25)
	DECLARE @TOTALROWS AS INT
	DECLARE @COUNTER AS INT 
	DECLARE @DUPLICATED AS INT
	DECLARE @INSERTCOUNTER AS INT

	SELECT @TOTALROWS = 1000
	SELECT @COUNTER = 0
	
	TRUNCATE TABLE DUPLICATES

	WHILE ( @COUNTER < @TOTALROWS)
	BEGIN
		SELECT @NAME = [Name] FROM [Name] WHERE ID = ROUND(RAND()*100,0)
		SELECT @INSERTCOUNTER = 0
		SELECT @DUPLICATED = ROUND(RAND()*10,0)
		WHILE (@INSERTCOUNTER < @DUPLICATED)
		BEGIN
			INSERT INTO DUPLICATES VALUES (@COUNTER + 1, @NAME)
			SET @INSERTCOUNTER = @INSERTCOUNTER + 1
		END
		SELECT @COUNTER = COUNT(*) FROM DUPLICATES
	END
	

