on: push
name: deploy
jobs: 
  deploy:
    name: deploy to a docker image
    runs-on: mcr.microsoft.com/mssql/server:2022-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker repository
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

