on: push
name: deploy
jobs: 
  deploy:
    name: deploy to a docker image
    runs-on: ubuntu-latest
    steps:
    - uses: 280780363/sqlserver-action@v1.0
      with:
        accept eula: Y #Required, ACCEPT_EULA confirms your acceptance of the End-User Licensing Agreement.
        sa password: EPAM1nt3rv13w # Optional, default value is SqlSever123123.
    - uses: actions/checkout@master
    - name: build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: vitocr9/sqlinterview
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
